apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policy.yaml
configMapGenerator:
  - name: no-latest
    namespace: gojsop-system
    files:
      - policy.js
    options:
      disableNameSuffixHash: true # policy.yaml refers to the ConfigMap by this name
