---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.gojsop.io
  resources:
  - jshooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.gojsop.io
  resources:
  - jshooks/finalizers
  verbs:
  - update
- apiGroups:
  - core.gojsop.io
  resources:
  - jshooks/status
  verbs:
  - get
  - patch
  - update
