apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hook.yaml
configMapGenerator:
  - name: count-pods
    namespace: gojsop-system
    files:
      - hook.js=dist/hook.js # written by npm run build
    options:
      disableNameSuffixHash: true # hook.yaml refers to the ConfigMap by this name
