apiVersion: core.gojsop.io/v1alpha1
kind: JSAdmission
metadata:
  labels:
    app.kubernetes.io/name: gojsop
    app.kubernetes.io/managed-by: kustomize
  name: add-team-label
spec:
  type: mutating
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE"]
  failurePolicy: Fail
  source:
    inline: |
      function mutate(req) {
        const obj = req.object;
        obj.metadata = obj.metadata || {};
        obj.metadata.labels = obj.metadata.labels || {};
        obj.metadata.labels.team = "frontend";
        return { allowed: true, modifiedObject: obj };
      }
